apiVersion: v1
kind: Secret
metadata:
  name: hradec-database-secret
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpuZXdwYXNzd29yZEAxMC4xMjguNDAuMjQ4OjU0MzIvbXlfZGF0YWJhc2U/c3NsbW9kZT1kaXNhYmxl
#cG9zdGdyZXM6Ly9teV91c2VyOlZOZXEzRlRrZk55V1Z2MFJAMTAuMTI4LjQwLjI0ODo1NDMyL215X2RhdGFiYXNlP3NzbG1vZGU9ZGlzYWJsZQ==
